from typing import Any, Callable

class User: ...
class HttpUser(User): ...

class Response:
    status_code: int
    def json(self) -> Any: ...

class HttpSession:
    def get(self, path: str, **kwargs: Any) -> Response: ...
    def post(self, path: str, **kwargs: Any) -> Response: ...
    def put(self, path: str, **kwargs: Any) -> Response: ...
    def delete(self, path: str, **kwargs: Any) -> Response: ...

def task(func: Callable[..., Any]) -> Callable[..., Any]: ...
def constant(seconds: float) -> Any: ...
